version: "3.8"

services:
  postgres:
    image: postgres
    container_name: pg-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
